name: mycodeservice
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  share_plus: ^6.3.0
  path_provider: ^2.0.11
  http: ^1.2.1
  sqflite: ^2.0.0
  provider: ^5.0.0
  flutter_barcode_scanner: ^2.0.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.1.2
  firebase_core: ^1.24.0
  firebase_auth: ^3.11.2
  cloud_firestore: ^3.1.6
  shared_preferences: ^2.0.8
  printing: ^5.12.0
  pdf: ^3.6.0
  ftpconnect: ^2.0.2

dependency_overrides:
  firebase_core_platform_interface: 4.5.1

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "imagenes/MYCODESERVICE.jpeg"

flutter:
  uses-material-design: true
  assets:
    - imagenes/logo.png
    - imagenes/profile.png
    - imagenes/MYCODESERVICE.png
    - imagenes/MYCODESERVICE.jpeg
    - json/articulos.json